### ISSUE TITLE
XY axis

### ISSUE THREAD

**Issue by Shadowtrance** [RelaxMX/Arduino-Bluetooth-GamePad#1]
Hi :)

Came across this on mitxela.com forum and i just happen to be building something similar to what you did with an arcade stick. 
Works great for buttons, but was wondering if you have any idea on how to add X Y axis for a joystick/Dpad movement?

Thanks and thanks for sharing. :)

**Comment by RelaxMX** [comment]
You could change JoyState function like this:

void JoyState(byte RYAxis, byte RXAxis, byte LYAxis, byte LXAxis, byte ST_BTN, byte ND_BTN) {
  Serial.write((byte)0xFD);   // HID raw report descriptor
  Serial.write((byte)0x6);    // Length
  Serial.write((byte)RYAxis);   // Right Y Axis 
  Serial.write((byte)RXAxis);   // Right X Axis 
  Serial.write((byte)LYAxis);   // Left Y Axis 
  Serial.write((byte)LXAxis);   // Left X Axis
  Serial.write((byte)ST_BTN); // fisrt 8 buttons
  Serial.write((byte)ND_BTN); //  last 8 buttons
}
